# Custom bindings for yazi - general goal is to make bindings similar to files.mini from Nvim
#
# Default Bindings
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Operations
  { on = "<Esc>", run = "quit", desc = "Close Yazi" },
	# { on = "s",         run = "open",                        desc = "Open selected files" },
	# { on = "S",         run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = "x",         run = "yank --cut",                  desc = "Yank selected files (cut)" },
	{ on = "d",         run = "remove",                      desc = "Trash selected files" },
	{ on = "D",         run = "remove --permanently",        desc = "Permanently delete selected files" },
  { on = "o",         run = "create",                      desc = "Create a file (ends with / for directories)" },
  { on = "i",         run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
  { on = "c",         run = "rename --cursor=start --empty=stem", desc = "Change name keeping extension" },
  { on = "z", run = 'shell --block -- ~/.config/yazi/scripts/ff_like_fzf_reveal.sh', desc = "fzf (ff-style) with live preview → cd/reveal" },
  { on = ["<Space>"], run = 'shell --block -- ~/.config/yazi/scripts/ff_like_fzf_reveal.sh', desc = "Toggle search (ff-style fzf with preview)" },

  # Copy (f-prefixed)
  { on = [ "f", "l" ], run = "copy path",             desc = "Copy the file path" },
  { on = [ "f", "d" ], run = "copy dirname",          desc = "Copy the directory path" },
  { on = [ "f", "f" ], run = "copy filename",         desc = "Copy the filename" },
  { on = [ "f", "n" ], run = "copy name_without_ext", desc = "Copy the filename without extension" },
	{ on = [ "s"],         run = "search --via=rg",             desc = "Search files by content via ripgrep" },
	{ on = "<Backspace>", run = [ "toggle", "arrow next" ], desc = "Toggle the current selection state" },#

	# Visual mode
	{ on = "v", run = "visual_mode",         desc = "Enter visual mode (selection mode)" },
	{ on = "V", run = "visual_mode",         desc = "Enter visual mode (selection mode)" },
	{ on = "a", run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },

  # Shortcuts
	{ on = "<D-f>", run = "find --smart",            desc = "Find next file" },
	{ on = "<S-D-f>",         run = "search --via=rg",             desc = "Search files by content via ripgrep" },

  # Macros
	{ on = "<S-F3>", run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = "<S-F4>", run = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = "<S-F6>", run = "arrow 50%",   desc = "Move cursor down half page" },

  { on = [ "0" ], run = "plugin relative-line-numbers 0", desc = "Jump (starts with 0)" },
  { on = [ "1" ], run = "plugin relative-line-numbers 1", desc = "Jump (starts with 1)" },
  { on = [ "2" ], run = "plugin relative-line-numbers 2", desc = "Jump (starts with 2)" },
  { on = [ "3" ], run = "plugin relative-line-numbers 3", desc = "Jump (starts with 3)" },
  { on = [ "4" ], run = "plugin relative-line-numbers 4", desc = "Jump (starts with 4)" },
  { on = [ "5" ], run = "plugin relative-line-numbers 5", desc = "Jump (starts with 5)" },
  { on = [ "6" ], run = "plugin relative-line-numbers 6", desc = "Jump (starts with 6)" },
  { on = [ "7" ], run = "plugin relative-line-numbers 7", desc = "Jump (starts with 7)" },
  { on = [ "8" ], run = "plugin relative-line-numbers 8", desc = "Jump (starts with 8)" },
  { on = [ "9" ], run = "plugin relative-line-numbers 9", desc = "Jump (starts with 9)" },

  { on = [ "g", "d" ], run = "cd ~/dotfiles", desc = "Go to Stow Dotfiles" },
  { on = [ "g", "l" ], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = [ "g", "o" ], run = "cd ~/Documents", desc = "Go to Documents" },
  { on = [ "g", "p" ], run = "cd ~/Projects", desc = "Go to Projects" },
  { on = [ "g", "e" ], run = "cd ~/Desktop", desc = "Go to Desktop" },
  { on = [ "g", "V" ], run = "cd ~/.config/Code/User", desc = "Go to Global VS Code config" },
  { on = [ "g", "n" ], run = "cd ~/.config/nvim", desc = "Go to NVim" },
  { on = [ "g", "c" ], run = "cd ~/.config", desc = "Go to Config" },

  { on = [ "g", "s" ], run = "cd ~/chrome/src", desc = "Go to Chrome src" },
  { on = [ "g", "b" ], run = "cd ~/chrome/src/out/Default", desc = "Go to Chrome Default Build out" },
  { on = [ "g", "v" ], run = "cd ~/chrome/src/.vscode", desc = "Go to Chrome VS Code config" },

  # Tabs
  { on = [ "b", "d" ], run = "close", desc = "Close current tab" },
  { on = [ "b", "n" ], run = "tab_create --current", desc = "New tab" },
]
