git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

# Do not pause after closing external tools like merge tools
promptToReturnFromSubprocess: false
promptToOpenMergeTool: false

os:
  editPreset: nvim

  # Make "open" (o) go to VS Code
  open: "code --reuse-window {{filename}}"

  # Open the current repo/folder in Code when the action is triggered
  openDirInEditor: "code --reuse-window {{dir}}"

gui:
  scrollHeight: 32
  scrollPastBottom: false
  scrollOffMargin: 8
  scrollOffBehavior: margin

keybinding:
  universal:
    undo: u
