name: Validate dotfiles on Linux and Windows

on:
  pull_request:
  push:
    branches: [ main, master, codex/** ]

jobs:
  linux-debian-testing:
    name: Debian testing (container)
    runs-on: ubuntu-latest
    container: debian:testing
    steps:
      - name: Install dependencies
        run: |
          set -euxo pipefail
          apt-get update -qq
          apt-get install -y -qq git curl ca-certificates rsync
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install chezmoi
        run: |
          curl -fsLS get.chezmoi.io | sh -s -- -b /usr/local/bin
          chezmoi --version
      - name: Prepare writable source
        run: |
          rsync -a . /work
      - name: Doctor
        run: |
          chezmoi doctor --source=/work --destination="$HOME"
      - name: Dry-run apply
        run: |
          chezmoi apply -n -v --source=/work --destination="$HOME"

  windows:
    name: Windows (PowerShell)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install chezmoi
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          iwr -useb https://get.chezmoi.io | sh -s -- -b $Env:USERPROFILE\bin
          "$Env:USERPROFILE\bin\chezmoi" --version
      - name: Doctor
        shell: pwsh
        run: |
          "$Env:USERPROFILE\bin\chezmoi" doctor --source="$PWD" --destination="$Env:USERPROFILE"
      - name: Dry-run apply
        shell: pwsh
        run: |
          "$Env:USERPROFILE\bin\chezmoi" apply -n -v --source="$PWD" --destination="$Env:USERPROFILE"

